# Generated by Django 5.2.4 on 2025-07-24 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellurance_app', '0002_emergency_incidentupdate_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responderassignment',
            name='responder_team',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellurance_app.emergency'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
