# Generated by Django 5.2.4 on 2025-07-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellurance_app', '0003_remove_responderassignment_responder_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
